default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: artifact_db

test:
  <<: *default
  database: artifact_db_test

production:
  <<: *default
  database: artifact_db_production